import type { Report } from '@/lib/types';

export const tapeheadsSubmissions: Report[] = [
  {
    id: 'rpt_001',
    operatorName: 'B. Johnson',
    shift: 1,
    date: new Date('2023-10-27T08:00:00Z'),
    status: 'Approved',
    shift_lead_name: "Lead A",
    th_number: "TH-1",
    material_type: "Carbon",
    end_of_shift_status: "Completed",
    shift_start_time: "06:00",
    shift_end_time: "14:00",
    total_meters: 1500,
    total_tapes: 15,
    issues: [],
    had_spin_out: false,
    checklist_items: { smooth_fuse_full: true, blades_glasses: true, spray_tracks_on_bridge: true, meter_stick: true },
    leadComments: 'Good work.'
  },
  {
    id: 'rpt_002',
    operatorName: 'S. Davis',
    shift: 1,
    date: new Date('2023-10-27T08:30:00Z'),
    status: 'Requires Attention',
    shift_lead_name: "Lead A",
    th_number: "TH-2",
    material_type: "Fiber",
    end_of_shift_status: "Completed",
    shift_start_time: "06:00",
    shift_end_time: "14:00",
    total_meters: 1200,
    total_tapes: 12,
    issues: [{ problem_reason: "Machine B jam", duration_minutes: 60 }],
    had_spin_out: true,
    spin_out_duration_minutes: 30,
    checklist_items: { smooth_fuse_full: true, blades_glasses: false, spray_tracks_on_bridge: true, meter_stick: true },
    leadComments: 'Please provide more details on the machine issue.'
  },
  {
    id: 'rpt_003',
    operatorName: 'A. Miller',
    shift: 2,
    date: new Date('2023-10-27T16:15:00Z'),
    status: 'Submitted',
    shift_lead_name: "Lead B",
    th_number: "TH-3",
    material_type: "Kevlar",
    end_of_shift_status: "In Progress",
    order_entry: "OE-12345",
    layer: "5",
    shift_start_time: "14:00",
    shift_end_time: "22:00",
    total_meters: 1800,
    total_tapes: 18,
    issues: [],
    had_spin_out: false,
    checklist_items: { smooth_fuse_full: true, blades_glasses: true, spray_tracks_on_bridge: true, meter_stick: true },
  },
  {
    id: 'rpt_004',
    operatorName: 'C. Wilson',
    shift: 2,
    date: new Date('2023-10-27T16:45:00Z'),
    status: 'Submitted',
    shift_lead_name: "Lead B",
    th_number: "TH-4",
    material_type: "Carbon",
    end_of_shift_status: "Completed",
    shift_start_time: "14:00",
    shift_end_time: "22:00",
    total_meters: 1600,
    total_tapes: 16,
    issues: [{ problem_reason: "Material shortage", duration_minutes: 15 }],
    had_spin_out: false,
    checklist_items: { smooth_fuse_full: true, blades_glasses: true, spray_tracks_on_bridge: false, meter_stick: true },
  },
  {
    id: 'rpt_005',
    operatorName: 'T. Moore',
    shift: 3,
    date: new Date('2023-10-28T00:30:00Z'),
    status: 'Submitted',
    shift_lead_name: "Lead C",
    th_number: "TH-5",
    material_type: "Polyester",
    end_of_shift_status: "Completed",
    shift_start_time: "22:00",
    shift_end_time: "06:00",
    total_meters: 2000,
    total_tapes: 20,
    issues: [],
    had_spin_out: false,
    checklist_items: { smooth_fuse_full: true, blades_glasses: true, spray_tracks_on_bridge: true, meter_stick: true },
  },
];
